### ISSUE TITLE
purge command

### ISSUE THREAD

**Issue by lyuxy** [nulli0n/ExcellentCrates-spigot#102]
Hi i am using excelent crate to give reward per day with daily reward system with one crate per month so i do one crate per month.
Is it possible to add command 

/excellentcrate reset all crate1
or /excellentcrate purgelimit crate1 ?
Otherwise I quickly find myself with a lot of useless data that I would like to delete every month.

thank you !

**Comment by nulli0n** [comment]
Done in v5.0.0
