### ISSUE TITLE
Command to see yours or others virtual keys not working/missing

### ISSUE THREAD

**Issue by Astolate** [nulli0n/ExcellentCrates-spigot#106]
(server version 1.19.4 - ecrates 4.3.0 - nexengine 2.2.10) 

The command to show players their own virtual keys or allow staff to look up others keys used to be `/ecrates key show` but no longer works/exists in the newest version. Is there a new command for players/staff to check their keys now or is it just not working?

https://github.com/nulli0n/ExcellentCrates-spigot/wiki/Permissions
`/crate key show` is still listed as the perm/command for viewing yours or others keys however is absent from the commands page.

**Comment by abhisantos** [comment]
I can confirm. the key show command is not working in the new version anymore.

**Comment by nulli0n** [comment]
Added back in v4.3.3
