### ISSUE TITLE
ExcellentCrates doesn't work

### ISSUE THREAD

**Issue by daniel-skopek** [nulli0n/ExcellentCrates-spigot#111]
Log: https://pastebin.com/raw/SyGaz5dR

Please test the plugin before releasing to the SpigotMC because it often doesn't work.

**Comment by joshwenke** [comment]
We have the same issue
https://pastebin.com/raw/6KrSTxsX

**Comment by DexterSK** [comment]
same issue

**Comment by joshwenke** [comment]
From the plug-in author on Spigot:
Redownload NexEngine. I messed up its updates/changes accidiently.
[#2677](https://www.spigotmc.org/threads/excellentcrates-advanced-custom-crates.280629/threads/excellentcrates-advanced-custom-crates.280629/page-134#post-4606079)

@daniel-skopek @DexterSK
