### ISSUE TITLE
[FEATURE] Permission node for crate mass open

### ISSUE THREAD

**Issue by Gabbysimon** [nulli0n/ExcellentCrates-spigot#116]
Hey! I noticed the new crate mass open feature, and I thought it would be cool if it could have a permission node that could be enabled to be required:

My idea:

A config line that lets you enable/disable the mass open permission `mass-open-permission: true/false`

When set to `true`, the mass open action (for example, Shift Right Click) requires the excellentcrates.massopen permission in order to work. When set to `false`, it works for everyone.

This idea is for a rank perk and is EULA compliant.

**Comment by nulli0n** [comment]
Done in v5.0.0
