### ISSUE TITLE
[FEATURE] %reward_amount% Placeholder

### ISSUE THREAD

**Issue by R00tB33rMan** [nulli0n/ExcellentCrates-spigot#120]
For winning a reward, allow users to show the amount they have won of a specific reward. Title indicates this more simplistically.

**Comment by nulli0n** [comment]
Could you explain more please?

**Comment by KingofAnomaly** [comment]
Sounds like they mean that if you have rewards of the same item but different amounts that the amount is displayed in the reward text. For an example if you had a crate that just gave gold ingots and a player got an option that gave 20 it would say they won 20 gold ingots.

**Comment by KingofAnomaly** [comment]
I would also like this feature and maybe add on the ability to set a range for the amount of items give as a single reward.
