### ISSUE TITLE
[BUG] Empty lore line removed

### ISSUE THREAD

**Issue by not-3than** [nulli0n/ExcellentCrates-spigot#121]
There is a bug in v4.4.0 (Using Paper 1.20.1)

When the crate gives a player the reward item, if a line of lore on the reward item is "" (nothing) then it will remove that line of lore, but if it is "&f" (or similar code, appearing the same), it will give that item with that line of lore.

Recreate:
1. Use v4.4.0
2. Apply line "" (empty line) of lore to item, put it in crate rewards
3. Win that item from the crate, and see that the lore has disappeared.

**Comment by nulli0n** [comment]
Not a bug. Put any color to make an empty line.
