### ISSUE TITLE
[BUG] Crate key giveall chat bug

### ISSUE THREAD

**Issue by not-3than** [nulli0n/ExcellentCrates-spigot#122]
In v4.4.0, using the giveall command for crate keys sends "You received x(amount) of (key)!" however many times of players online to the original command sender.

Expected behavior is that these messages are sent to the players receiving the keys, and not to the command sender.

Here is a screenshot:
![crate keyall bug](https://github.com/nulli0n/ExcellentCrates-spigot/assets/67490606/1dbc5d38-2998-431e-ad4a-8715d2d5e0f3)

**Comment by nulli0n** [comment]
Fixed in the latest release.
