### ISSUE TITLE
Empty lore line removed

### ISSUE THREAD

**Issue by aquiurbex** [nulli0n/ExcellentCrates-spigot#123]
When with ItemEdit I set line 2 of the lore to a text, and line 1 remains empty, when granting the reward, it ignores line 1 and eliminates it, thus putting line 2 in the place of line 1, etc.
If, on the other hand, I put a color code without anything (&f) on the empty line, it does not ignore it and if it gives the reward with that line without text.
I would like the reward to be delivered if the line is empty.

**Comment by nulli0n** [comment]
Disable PlaceholderAPI in the config.yml if it's enabled. This plugin does not modify reward items in any way.
