### ISSUE TITLE
Key not being removed?

### ISSUE THREAD

**Issue by Bufferless** [nulli0n/ExcellentCrates-spigot#128]
I encountered this issue a few months ago and it's happening again. When players use the crates, their keys are not being removed as they should be. The keys break randomly and it's becoming increasingly frustrating.

There haven't been any errors, and this issue was dormant for some time until I logged on recently.

I'm using the latest version of ExcellentCrates, which is 4.4.2, as well as the latest version of NextEngine.

**Comment by nulli0n** [comment]
Send your ExcellentCrates folder
