### ISSUE TITLE
Hologram don't work

### ISSUE THREAD

**Issue by aesopcmc** [nulli0n/ExcellentCrates-spigot#137]
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/25699609/eb04d8b0-e1ae-46e4-bf03-1039b87d8d28)
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/25699609/0f3493f0-8d5b-4793-871a-cead40c04eb3)

ExcellentCrates : 5.0.0
Minecraft:1.19.3

**Comment by TylBurxyz** [comment]
Have you tried changing to a different hologram template?

**Comment by aesopcmc** [comment]
> Have you tried changing to a different hologram template?

What does a hologram template mean? Isn't it text? Is it a sign pointing to another plugin?

**Comment by aesopcmc** [comment]
thanks! i found it
