### ISSUE TITLE
Offhand Key Consumption

### ISSUE THREAD

**Issue by TylBurxyz** [nulli0n/ExcellentCrates-spigot#138]
Versions
Paper: git-paper-226 (1.20.2)
ExcellentCrates: 5.0.0
NexEngine: 2.2.12

Issue
When holding a crate key in the offhand slot, players can open the linked crate without consuming said key.  Allowing players to have one key in their offhand and open the crate as many times as they want to.

**Comment by nulli0n** [comment]
Redownload NexEngine to fix that.
