### ISSUE TITLE
Setting Display Particle RGB - Blue not working

### ISSUE THREAD

**Issue by TheSkullyKO** [nulli0n/ExcellentCrates-spigot#144]
Setting the RGB of the display particles via the command does not get put into the yml file.
Putting [0,0,255] [1] gives black particles. Putting [0,255,255] [1] gives green particles.
Checked the yml and the blue value was still showing 0.
Changed the value manually in the yml to show 0,255,255, and reloaded it in the game, particles turned to cyan just fine.
The bug is just in the command setting the value.

Thanks :D

**Comment by nulli0n** [comment]
Fixed in v5.2.0
