### ISSUE TITLE
2 issues with new version of ExcellentCrates

### ISSUE THREAD

**Issue by Dagrond** [nulli0n/ExcellentCrates-spigot#146]
Hey, I've just updated to excellentcrates v5.0.0 and it has 2 bug that I've discovered so far:

1. With the new version you cannot add reward that force open different crate for player. E.G. If you add an reward that is executing command "excellentcrates open somecrate %player_name% -s -f" is does nothing. That was working fine on v4 version of the plugin. 

2. You cannot change display name of a key. I mean, you can, but it is returning to default name every restart.

**Comment by nulli0n** [comment]
Fixed in v5.2.0
