### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Vally90** [nulli0n/ExcellentCrates-spigot#147]
With the latest version of the ExcellentCrates plugin (5.0.0), when a player holds the key in their off-hand, they can open the crate an infinite number of times without consuming the key. This issue wasn't present in the previous version. Is this a known bug or not? It's quite dangerous if discovered by players as it allows them to infinitely open crates.

**Comment by nulli0n** [comment]
Update NexEngine.
