### ISSUE TITLE
Setting the opening keys

### ISSUE THREAD

**Issue by Hellw0rker** [nulli0n/ExcellentCrates-spigot#150]
Right-clicking the case in /gamemode adventure mode opens and discards the case at the same time. How to fix that the player only pushes back, without opening the case ?

https://github.com/nulli0n/ExcellentCrates-spigot/assets/99292648/d6d044f4-16f4-481c-b735-d2e6cf791820

**Comment by Hellw0rker** [comment]
@nulli0n , please help me with this question.

**Comment by nulli0n** [comment]
This is a spigot/paper "bug". Just use non-interactable blocks. Nothing to fix on my side.
