### ISSUE TITLE
[Feature Suggestion] Crate Location Cooldowns

### ISSUE THREAD

**Issue by KingofAnomaly** [nulli0n/ExcellentCrates-spigot#152]
The ability to have location based cooldowns. An example of this would be if you have two different locations of the same crate, a player would be allowed to click on one location and activate the cooldown for that one only then be able to click on the next location and activate a separate cooldown. This would make the plugin easily be used in minigames to generate random loot for players or to make daily reward chests hidden around spawn.

**Comment by nulli0n** [comment]
Currently not interested in this.
