### ISSUE TITLE
[Feature Suggestion]

### ISSUE THREAD

**Issue by kokqi** [nulli0n/ExcellentCrates-spigot#153]
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/78592988/a7d90ee1-a786-44ee-87a7-a5c9e0729fe3)
FEATURE SUGGESTION:
consume the crate key that I'm currently holding instead of the key that I'm not currently holding

**Comment by nulli0n** [comment]
Extra calculations for no reason.
