### ISSUE TITLE
Ghost item from the crates

### ISSUE THREAD

**Issue by PyrexPacks** [nulli0n/ExcellentCrates-spigot#155]
Hi!
Some players discovered, that if you inspect a crates items, and hover at an item, and press F (or the keybind you have to put the items in your offhand), and use a injection hack called doomsday with pingspoofer at the maximum, while the xcarry is on, they can put the ghost items to their inventory, but they can also turn this item into normal items!
I dont know how the players turn the items into normal items.
And does anyone know how do these people get in hold of god items, like sharpness 100 swords? No admin gave these to them.
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/126282272/3428158f-2cd2-4829-baa8-951d295c00d4)
![Minecraft_Screenshot_2024 01 06_-_19 16 40 36](https://github.com/nulli0n/ExcellentCrates-spigot/assets/126282272/b5825e80-197b-4c48-8dea-2acd96b515e7)
![Minecraft_Screenshot_2024 01 06_-_17 27 14 66](https://github.com/nulli0n/ExcellentCrates-spigot/assets/126282272/2de39477-71a0-4d27-a5cc-181c2797da03)

Video:

https://github.com/nulli0n/ExcellentCrates-spigot/assets/126282272/9d42a2e3-8cc6-44e2-ace0-304b76e54488

**Comment by nulli0n** [comment]
no comments
