### ISSUE TITLE
Chest as crate block

### ISSUE THREAD

**Issue by jfoucher** [nulli0n/ExcellentCrates-spigot#165]
When I use a chest as a crate opening block and I don't have a key, the chest opens and I can its contents (it is empty) I expected just the pushback to happen and nothing else. It worked that way until not long ago.

Is there a configuration I can change to have excellent fully override the right click ?

Thanks

**Comment by iLuckyx** [comment]
We had the same issue, I created WorldGuard sub regions and disabled chest access.

**Comment by nulli0n** [comment]
Already works this way by overriding interactions with crate blocks. There was no changes in this. Must be there is something on your side.
