### ISSUE TITLE
[ExcellentCrates] Plugin ExcellentCrates v5.0.0 generated an exception while executing task 8177

### ISSUE THREAD

**Issue by Tomask4** [nulli0n/ExcellentCrates-spigot#167]
[ExcellentCrates] Plugin ExcellentCrates v5.0.0 generated an exception while executing task 8177:
this warning is shown in my console for houndreds of times and every time i place a crate is places the first crate i placed after the last restart... What is going on here? Please help me its driving me crazy

**Comment by nulli0n** [comment]
Fixed in v5.2.0
