### ISSUE TITLE
Keys not stacking

### ISSUE THREAD

**Issue by Mousycritter** [nulli0n/ExcellentCrates-spigot#168]
Keys that are acquired at different times won't stack. 

https://cdn.discordapp.com/attachments/1218713692900818974/1218713768372994108/image.png?ex=6608aaa4&is=65f635a4&hm=da083fd0498f823b2e70d124d91361185e5ab453d9b27c20186b27afd957169d&

https://cdn.discordapp.com/attachments/1218713692900818974/1218713768889024613/image.png?ex=6608aaa5&is=65f635a5&hm=5bc6d47d9ac186efcb69b516f2488114c3d31859e1f59664af60ac797c82f2a6&

Discord image links

**Comment by iLuckyx** [comment]
The links do not work and say the content is no longer available. 

Additionally, hold the items in your hand and if you're running paper, run command `/paper dumpitem`. Also explain how each of the keys were obtained; ex. crates, player trading, give command, etc.

**Comment by Mousycritter** [comment]
The images were just keys that won't stack. They were monthly crate keys that we're obtained at different times and didn't allow me to stack them.

**Comment by iLuckyx** [comment]
If I had to imagine the NBT of the keys changed. Running `/paper dumpitem` should give some indicators.

**Comment by nulli0n** [comment]
Items with different NBT data won't stack. Make sure you don't have plugins that can modify player items and you didn't change key items.
