### ISSUE TITLE
Where can I add more hologram templates?

### ISSUE THREAD

**Issue by fwsrr** [nulli0n/ExcellentCrates-spigot#169]
Since new update you cant add or remove single lines but only have a template active.
Im wondering how and where i can add / remove / edit these templates.
Thanks
![2024-03-17_11 19 17](https://github.com/nulli0n/ExcellentCrates-spigot/assets/154999271/fcf0c36e-a0a4-4db2-9dd5-6dae19e953f2)

**Comment by iLuckyx** [comment]
Templates are found in the config.yml
