### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by EisigerRexi** [nulli0n/ExcellentCrates-spigot#171]
**Dear programmer of this plugin**!

I wanted to display the number of keys to display in a scoreboard using the PlaceholderAPI, but the specified placeholders (from the page https://github.com/nulli0n/ExcellentCrates-spigot/wiki/PlaceholderAPI) don't work.

If you want to download Westmal, the plugin is not available from PlaceholderAPI.

What am I doing wrong?

**Best regards
EisigerRexi**

PS: Sorry for the bad (translator) English

**Comment by iLuckyx** [comment]
I do not have any issues on my server with the placeholders. 
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/35910221/a715c8b8-6f4c-4247-9262-1a723624f55c)
`- '%excellentcrates_keys_vote%'`

I'd make sure your key id is correct, and the placeholder. Verify you're running the latest versions.

**Comment by EisigerRexi** [comment]
the "vote" is this the ID?
