### ISSUE TITLE
Key display name not saving on its own

### ISSUE THREAD

**Issue by gecko10000** [nulli0n/ExcellentCrates-spigot#174]
When editing the key display name, it will not be saved until something like the display item is edited.

For a minimum reproducible example, create a key and change its name. Look at the key config and you will see that it's unchanged. `/crates reload` will confirm that it has not been saved. Now, do the same but also set an item for the key. The item will be saved, along with the key name.

**Comment by nulli0n** [comment]
Fixed in v5.2.0
