### ISSUE TITLE
[!] Placeholders problem after update + message bug in chat

### ISSUE THREAD

**Issue by smscentras** [nulli0n/ExcellentCrates-spigot#175]
![editor](https://github.com/nulli0n/ExcellentCrates-spigot/assets/130366229/a6df6ff8-2a80-4d0b-bbd7-7234d8adb238)

And message, after plugin prefix go to next line with message
"**[Crates]
Player opened crate and win...**"

**Comment by nulli0n** [comment]
1. You need to reset some entries in lang config under `Editor` section (or just the whole Editor section).
2. Use `<noprefix>' tag

**Comment by smscentras** [comment]
<noprefix> not help
