### ISSUE TITLE
[Bug?] Left-Click to preview acts as Open Crate.

### ISSUE THREAD

**Issue by ClickErrorxD** [nulli0n/ExcellentCrates-spigot#178]
Using ExcellentCrates-5.2.1.jar and nightcore-2.5.2.jar, left-clicking on a crate to preview no longer works like it used to, it's more annoying than anything.
1. If you have a key inside your inventory, and you go to left-click to view the contents of the crate for that key, it opens it.
2. If you don't have a key in your inventory, the preview opens, but you get knocked back and the title messages saying you do not have a key.
My current Click Actions:
`  Click_Actions:
    SHIFT_RIGHT: CRATE_MASS_OPEN
    RIGHT: CRATE_OPEN
    LEFT: CRATE_PREVIEW`

**Comment by nulli0n** [comment]
Nothing were changed in this. I'm unable to reproduce it and it works just fine for me as before.

**Comment by ClickErrorxD** [comment]
Imma tr

> Nothing were changed in this. I'm unable to reproduce it and it works just fine for me as before.

I'll experiment a bit more. I noticed one of the crates i created after updating doesn't do it. This is so weird.

**Comment by ClickErrorxD** [comment]
Turns out, it's only while im OP'd. So I guess imma just not worry about it anymore.

**Comment by Sh3r1ffCZ** [comment]
> Nothing were changed in this. I'm unable to reproduce it and it works just fine for me as before.

Hello, 
 today I tested the new version(ExcellentCrates-5.2.2.1.jar) on my server (1.20.4) and I have the same problem. When the opening animation is set on the case, it can't open multiple keys at once. However, when I set any animation, there is no problem. 
Only the sound during the animation is about 30 times louder, as I open of course 30 keys at once.

**Comment by ClickErrorxD** [comment]
> > Nothing were changed in this. I'm unable to reproduce it and it works just fine for me as before.
> 
> Hello, today I tested the new version(ExcellentCrates-5.2.2.1.jar) on my server (1.20.4) and I have the same problem. When the opening animation is set on the case, it can't open multiple keys at once. However, when I set any animation, there is no problem. Only the sound during the animation is about 30 times louder, as I open of course 30 keys at once.

I gave up with the issues ngl, updating broke a lotta things.
For the sound, https://github.com/nulli0n/ExcellentCrates-spigot/issues/179 I suggested something.
