### ISSUE TITLE
[BUG] I get a reward 100% of the time.

### ISSUE THREAD

**Issue by Plexi09** [nulli0n/ExcellentCrates-spigot#180]
I added a reward with a 1% chance, but i get it all the time

**Comment by gecko10000** [comment]
Yes, the chances are scaled to fit 100%. If you have two items with a 1% chance each, they will scale up to a 50% chance. If you want to actually have a 1% chance of getting a reward, you could add a dummy reward that takes up the other 99% so it doesn't scale properly.

**Comment by Plexi09** [comment]
I know, but i have 25 other items with 10% each

**Comment by nulli0n** [comment]
https://nightexpress.gitbook.io/excellentcrates/features/rarity-weights-and-chances
