### ISSUE TITLE
Crate Opening Breaks After Shift+Right Clicking

### ISSUE THREAD

**Issue by gecko10000** [nulli0n/ExcellentCrates-spigot#182]
When a player shift+right clicks on a crate with a stack of keys, the crate will be opened once. After this, all crate keys (not just for that crate) will cease to work for that player until they relog. However, the player will still receive the "you don't have a key for this crate" title and get pushed back when they don't have a key when right-clicking a crate, but only get pushed back when they do.

**Comment by nulli0n** [comment]
Should be fixed in v5.2.2.2
