### ISSUE TITLE
ExcellentCrates generated an exception

### ISSUE THREAD

**Issue by Nch0001** [nulli0n/ExcellentCrates-spigot#184]
10.05 23:46:57 [Server] [WARN] [ExcellentCrates] Task #141177 for ExcellentCrates v5.0.0 generated an exception
10.05 23:46:57 [Server] [INFO] java.lang.ArrayIndexOutOfBoundsException: null

**Comment by Nch0001** [comment]
10.05 23:54:24 [Server] [WARN] [ExcellentCrates] Task #70 for ExcellentCrates v5.2.2.1 generated an exception
10.05 23:54:24 [Server] [INFO] java.lang.ArrayIndexOutOfBoundsException: null
this is with the newest ver

**Comment by nulli0n** [comment]
This is useless. Next time send full logs.
