### ISSUE TITLE
CRATE_MASS_OPEN bug for most bedrock clients

### ISSUE THREAD

**Issue by efor89** [nulli0n/ExcellentCrates-spigot#185]
hi
if a bedrock player(tested with handy and tablet) do CRATE_MASS_OPEN he opens only 1 crate and the keys are not removed, sometimes the player becomes more keys.
so he can open endless crates.
(win10 version have no problems)

testet with paper 1.20.4 server

**Comment by nulli0n** [comment]
Should be fixed in v5.2.2.2

**Comment by efor89** [comment]
now if i open 1 key is removed and 1-2 sec later i become the key back.
i become everytime 1 reward.
i see everytime the msg: you have to wait 5sec to open again.
