### ISSUE TITLE
Rewards not working. 

### ISSUE THREAD

**Issue by TrickyFNFexe** [nulli0n/ExcellentCrates-spigot#187]
Server version: Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
Plugin version: ExcellentCrates version 5.2.2.1

I have this issue, where once I add the rewards into the crate and then restart the server. All the rewards that I just added gets deleted. Like there's a barrier and it says: "Reward gives nothing". I do not know how to fix this issue. I have tried everything, from deleting the the whole Excellentcrates folder, to make the plugin regenerate it. Nothing works. Please Any help!

![Screenshot 2024-05-15 164918](https://github.com/nulli0n/ExcellentCrates-spigot/assets/84867232/003fad77-963d-4eaa-b3d5-5824eae1cac0)

**Comment by TrickyFNFexe** [comment]
Any help please?

**Comment by nulli0n** [comment]
What items you're trying to put in?

**Comment by TrickyFNFexe** [comment]
netherite sword, with a custom name. The name is: "&a&lGreen Saber MK4"

**Comment by nulli0n** [comment]
Is it comes from some custom item plugin?

**Comment by TrickyFNFexe** [comment]
no, I don't have any custom items plugin. I do have an item visualizer. After removing that doesn't fix the issue. Any suggestions?

**Comment by TrickyFNFexe** [comment]
Is it because, the netherite sword is a custom item from a texture pack? It can't be right. Because it worked before, now it's all broken. Maybe another plugin interfering with this?

**Comment by nulli0n** [comment]
Send your crate config file

**Comment by Nottt-sys** [comment]
i got the same problem

[config.txt](https://github.com/user-attachments/files/15764872/config.txt) (After 1 restart)

[config (2).txt](https://github.com/user-attachments/files/15764886/config.2.txt) (After 2 restarts)
Both dont have working items they just turn into a barrier
![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/172269407/fd885f7e-9e09-4bff-89a0-c44a7b9305c3)
(was previously a named elytra using /itemrename

**Comment by Nottt-sys** [comment]
[rare.txt](https://github.com/user-attachments/files/15764911/rare.txt)
Here is the create after the item turns into a barrier

**Comment by TrickyFNFexe** [comment]
I think there is a similar issue, where I believe I used something similar to this command:
`/give @a netherite_sword{display:{Name:'["",{"text":"test","italic":false,"color":"dark_red","bold":true}]'}}`

and I also believe I also used `/itemrename`. Therefore I believe something to do with renaming or colors?

**Comment by TrickyFNFexe** [comment]
@Nottt-sys  's config has the same thing: `&7&l⭐2 Thanos Elytra ⭐`. Where `&7&l` is clearly from /itemrename.

**Comment by TrickyFNFexe** [comment]
@nulli0n  can't send you config, as the server that I was developing deleted all their files in order to start a new season, and all backups were also deleted. I may try to get in contact with the server manager hoping to obtain that backup file. Because he creates a backup of every season, just in case.

**Comment by TrickyFNFexe** [comment]
I will try to recreate this, today.

**Comment by TrickyFNFexe** [comment]
"reward gives nothing"

**Comment by nulli0n** [comment]
I only need a crate file with original items that are turning into barriers on plugin reload. All other info is useless.

**Comment by nulli0n** [comment]
Fixed in v5.3.0
