### ISSUE TITLE
Custom Item Name not displayed

### ISSUE THREAD

**Issue by LarcekGiglamesh** [nulli0n/ExcellentCrates-spigot#188]
Versions:
- CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
- ExcellentCrates-5.2.2.1
- nightcore-2.5.2.1

Applying a custom Name to an item is only being printed correctly in the Editor, but not in the preview or an actual Block position. 

![2024-05-17_16 06 17](https://github.com/nulli0n/ExcellentCrates-spigot/assets/19149222/7d5fb88c-37c9-4c68-8979-9db0be9745c3)
![2024-05-17_16 06 36](https://github.com/nulli0n/ExcellentCrates-spigot/assets/19149222/c80fa0ac-09ed-46da-b814-f608edbd91b1)
![2024-05-17_16 06 42](https://github.com/nulli0n/ExcellentCrates-spigot/assets/19149222/a19f407e-d8e6-40dd-9ce5-475b48934208)

**Comment by nulli0n** [comment]
It clearly says that display name is used in messages and placeholders only.
