### ISSUE TITLE
Issue with custom items 

### ISSUE THREAD

**Issue by Veyjinn** [nulli0n/ExcellentCrates-spigot#192]
Hi! Recently I've been testing your plugin first of all I would like to say that its really amazing! Custom GUI, crate opening animations, the overall functionality and the customization possibilities... All really handy!

Now regarding the issue I'm writing about:

Custom items that are part of my crate loot and are not identical to its original. It seems like Excellent crates can't recreate the exact same item. 

ExcellentCrates-5.2.2.3
paper-1.20.4-496

https://github.com/nulli0n/ExcellentCrates-spigot/assets/59097595/a0fd4842-4798-4fce-8fea-c7cf60b16225

**Comment by TrickyFNFexe** [comment]
I think this is the same issue that I have been facing. I made a issue report on this some time back(I think 2 weeks ago XDD).

**Comment by TrickyFNFexe** [comment]
I think the issue is that the NBT has reset after you get the item? or no? because for my crate, I used a CustomModelData tag for a custom items(my texture pack) and it was facing some issues. I put it in a crate and it turned into a barrier, saying that this item doesn't exist.

**Comment by TrickyFNFexe** [comment]
I think there is a issue with texture packs(I am thinking about `CustomModelData`), or i am just wrong.

**Comment by TrickyFNFexe** [comment]
because I think your ruby that you have created from a texture pack it has a custom model data.

**Comment by TrickyFNFexe** [comment]
my issue report: https://github.com/nulli0n/ExcellentCrates-spigot/issues/187

**Comment by Veyjinn** [comment]
Yeah its most likely related to custommodeldata and NBT

**Comment by nulli0n** [comment]
1. Do /paper dumpitem and compare them
2. Just the reward commands to give custom items especially from ItemsAdder and similar plugins.

**Comment by Veyjinn** [comment]
Okay, I used /paper dumpitem

1. The Original item

`minecraft:diamond{CustomModelData: 1, display: {Name: '[{"text":"Ruby","italic":false,"color":"#ff0033","bold":true}]', Lore: ['[{"text":"A beautifully red (and rare!) gemstone","italic":false,"color":"red"}]']}}`

2. The item version from the crate:

`minecraft:diamond{CustomModelData: 1, display: {Name: '{"text":"","extra":[{"text":"Ruby","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#FF0033","bold":true}]}', Lore: ['{"text":"","extra":[{"text":"A beautifully red (and rare!) gemstone","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"red","bold":false}]}']}}`

Ok so we can see these two versions of the Ruby item are different. The problem is that the lenght of the command can be sometimes longer than the chat limit and as far as I know the lenght of the chat can't be modified, so not every command will fit
