### ISSUE TITLE
holding button for crate_mass_open bypasses limits

### ISSUE THREAD

**Issue by LadyUnicornEJG** [nulli0n/ExcellentCrates-spigot#193]
With shift_right set to crate_mass_open and mass_opening_limit set to 64, I gave myself 1000 keys to run a test and held shift+right click. Even if I let go after a second, it kept opening keys (not just finishing the current stack). Setting hold_key_to_open to true caused this to be limited to a max of 9 stacks (hotbar, starts with slot 1 but once slot 9 is done you aren't holding the key anymore), but obviously even 9 stacks at once can cause some issues. I also attempted setting a cooldown, but that appears to be completely ignored by mass opening (even setting it to 60 seconds didn't stop it from opening several stacks in a few seconds instead of just 1 stack).

**Comment by nulli0n** [comment]
I was unable to reproduce all of these. Of course you can spam it, but it does not bypasses the limit and not consumes all the keys in a single opening. You also probably have cooldown bypass permissions. Just use the latest plugin version.
