### ISSUE TITLE
Reward previews reset after updating to 1.20.6/1.21

### ISSUE THREAD

**Issue by alfredcort** [nulli0n/ExcellentCrates-spigot#196]
Once updating my server to 1.20.6 (along with updating ExcellentCrates & Nightcore), the preview names of the rewards got completely reset to the vanilla Minecraft name.

Here's a video of what I mean by the name previews being reset: https://i.imgur.com/nu56NsE.mp4

Is there anything I can do to make this an easier fix than to fixing it manually?

**Comment by ExpertSneeker** [comment]
I also encountered this situation

**Comment by efor89** [comment]
yes i was have the same problem but i setup all new now. -.-

**Comment by nulli0n** [comment]
Fixed in v5.3.0
