### ISSUE TITLE
Keys are sometime not given

### ISSUE THREAD

**Issue by efor89** [nulli0n/ExcellentCrates-spigot#199]
Hey,
sometimes i see the msg in console that the key is given but if i looking ingame i missing a key.
is german: [Fr. 22:50:46 INFO ] PromiCrates » Es wurden x1 Legendary Key  .GedichtAmoebe24 gutgeschrieben.
the console msg says he become a key but he dont become the key.
i have also sometime i vote(console say i receve a key) and i not become the key ingame.

**Comment by nulli0n** [comment]
Fixed in v5.3.0
