### ISSUE TITLE
help command is not displaying commands

### ISSUE THREAD

**Issue by Sylensky** [nulli0n/ExcellentCrates-spigot#2]
ExcellentCrates version 4.0.3.3
Spigot version: git-Paper-170 (MC: 1.18.1)

Entering `/excellentcrates` just displays the following but should show the overall help i assume.
![image](https://user-images.githubusercontent.com/57076968/150661909-99da0a6b-61b6-499c-b8b2-91b7faee0d13.png)

**Comment by nulli0n** [comment]
Reset /NexEngine/lang folder.

**Comment by Sylensky** [comment]
That does not fix the issue.
