### ISSUE TITLE
Unable to create crates

### ISSUE THREAD

**Issue by Cruwzky** [nulli0n/ExcellentCrates-spigot#204]
Server version: Paper 1.21-123
ExcellentCrates: 5.3.1
Nightcore: 2.6.3

Then doing the following
1. Run "/crate editor"
2. Press "Crates"
3. Press "New Crate"
4. It asks to "Input Mode Enter [Crate Identifier]" then typing something in chat and sent it the following error comes in console: https://mclo.gs/ntdVoEm

I am testing on a clean server without any other plugins.

**Comment by nulli0n** [comment]
https://github.com/nulli0n/nightcore-spigot/releases/tag/v2.6.3-updated
