### ISSUE TITLE
Crates will not open even if there is a key in hand

### ISSUE THREAD

**Issue by AlexButHimself** [nulli0n/ExcellentCrates-spigot#21]
Im trying to make a crate for a server but every time i try to open it, It tells me i dont have it
Even though that I have the key that i assigned in my hand, it still says i dont have it
please fix

**Comment by byNixo** [comment]
I have the same problem. Please fix as soon as possible.

**Comment by Animationking11** [comment]
Can you send a video of the bug @byNixo @AlexButHimself

**Comment by nulli0n** [comment]
Unable to reproduce
