### ISSUE TITLE
Crate Cooldown not Updating for players.

### ISSUE THREAD

**Issue by InvisibleSpiders** [nulli0n/ExcellentCrates-spigot#210]
Nightcore 2.6.3
eCrates 5.3.1
Paper 1.21 B 127

If your player is on cooldown for opening a crate, but then you remove the cooldown from the crate requirements, players are stuck on the cooldown until either time expires, or the admin runs the "resetcooldown" command on each affected player.

Persists through a plugin reload, as well as server restart.

Minor inconvenience, but worth a share.

**Comment by nulli0n** [comment]
fixed in v5.3.2
