### ISSUE TITLE
Crate preview and hologram not working

### ISSUE THREAD

**Issue by Daan13000** [nulli0n/ExcellentCrates-spigot#221]
I have one crate where the preview doesn't work and none of the holograms load. Im not sure wat the issue is.
![2024-09-11_23 04 35](https://github.com/user-attachments/assets/eb6b8667-0efa-4f6c-bade-fe6bd4cabd22)

**Comment by Daan13000** [comment]
My server runs on spigot, i have night-core installed.

**Comment by nulli0n** [comment]
Read manual for hologram requirements.
