### ISSUE TITLE
Empty config files

### ISSUE THREAD

**Issue by GeneralT123** [nulli0n/ExcellentCrates-spigot#223]
![Knipsel](https://github.com/user-attachments/assets/1bea0faf-4338-4e85-b68a-7968d5c5ccc9)

When I downloaded the plugin, right away it didn't allow me to run any commands. When I checked the config files they were completely empty. I tried different versions of the plugin but non of them seemed to fix the problem.

**Comment by nulli0n** [comment]
Read plugin requirements.
