### ISSUE TITLE
Crates & Keys not working in the 5.3.3 update

### ISSUE THREAD

**Issue by ChiefWarPig** [nulli0n/ExcellentCrates-spigot#224]
Hi, I have had to downgrade the plugin back to 5.3.2 due to the plugin generating an exception and not working when trying to open crates. Keys can also not be obtained via command but instead you have to get them from the /crate editor. Logs of console errors for your refference. 
https://mclo.gs/lj1ND4b

**Comment by nulli0n** [comment]
Fixed in reuploaded latest version.
