### ISSUE TITLE
%crates_(something)% Placesholders don't work & RGB Color Codes don't work for some Crates

### ISSUE THREAD

**Issue by FOrt304** [nulli0n/ExcellentCrates-spigot#227]
![Some Crates have broken RGB Color Codes - Vote Crate](https://github.com/user-attachments/assets/fe22a614-1a44-4a70-a167-376e7582d4a4)
![Normal look of a Crate - Cheese Crate](https://github.com/user-attachments/assets/8a8acdd0-f9f3-4bd3-875b-8e68620febbc)
![Crate Placeholders Broken](https://github.com/user-attachments/assets/13a98f22-862b-4eab-98e7-2d9840babfad)

**Comment by nulli0n** [comment]
update nightcore
reset lang config
