### ISSUE TITLE
open wont work

### ISSUE THREAD

**Issue by luckychampsishere1** [nulli0n/ExcellentCrates-spigot#228]
I made all the crates and keys and I've linked the keys with crates but when I get a key , the crate won't open and it just pushes me back even though I'm holding the key for the crate.

**Comment by SiuanSong** [comment]
> I made all the crates and keys and I've linked the keys with crates but when I get a key , the crate won't open and it just pushes me back even though I'm holding the key for the crate.

It seems you now need to restart after creating a new crate for that new crate to work. I was having the same issue today and was very confused why it wasn't working right away, as I've used this plugin for years and, to the best of my recollection, a restarts not ever been needed for that before. >.<

**Comment by nulli0n** [comment]
Not true, restart won't change anything
