### ISSUE TITLE
Item preview lore color bug

### ISSUE THREAD

**Issue by Cruwzky** [nulli0n/ExcellentCrates-spigot#30]
There is a bug in the item preview. In some circumstances it's showing the wrong color in the lore of the item.

**Item in inventory:**
![image](https://user-images.githubusercontent.com/20445289/175952204-43d327e6-c0e2-4de8-b71b-f53bf1903e33.png)

**Item in preview:**
![image](https://user-images.githubusercontent.com/20445289/175952154-13608ee1-dc0f-49a0-a1c0-54a23f13aa89.png)

Give command for the item in the screenshots:
`/minecraft:give @p minecraft:elytra{CustomModelData:1,EntityTag:{Invisible:1b},display:{Name:'[{"text":"Dragonscale Wings","italic":false,"color":"red"}]',Lore:['[{"text":"test","italic":false,"color":"red"},{"text":"]","italic":false,"color":"dark_gray"}]','[{"text":"[test]","italic":false,"color":"dark_gray"}]','[{"text":"[","italic":false,"color":"dark_gray"},{"text":"test","color":"gold"},{"text":"]"},{"text":"","color":"dark_purple"}]','[{"text":"test","italic":false,"color":"gold"},{"text":"]","color":"dark_gray"}]']},Enchantments:[{id:"minecraft:infinity",lvl:1},{id:"minecraft:unbreaking",lvl:4}],HideFlags:126} 1`

I am running Purpur 1.19 build 1669 and ExcellentCrate version 4.0.5

**Comment by nulli0n** [comment]
There is a mistake in your command, it has 'dark_purple' color. Not the plugin issue.

**Comment by Cruwzky** [comment]
I see why you think that but the give command is formatted correct. The dark purple is not applied to any text.

I have created another command where the dark purple is not there. And ExecellentCrates still does not show it correct. So im pretty sure there is a bug in the preview of the items.

`/minecraft:give @p minecraft:stone{display:{Name:'[{"text":"test item","italic":false}]',Lore:['[{"text":"test","italic":false,"color":"green"},{"text":"]","color":"dark_gray"}]','[{"text":"[","italic":false,"color":"dark_gray"},{"text":"test","color":"dark_green"}]','[{"text":"[","italic":false,"color":"dark_gray"},{"text":"test","color":"dark_blue"},{"text":"]"}]','[{"text":"test","italic":false,"color":"red"}]']}} 1`

Item I put into the preview slot:
![image](https://user-images.githubusercontent.com/20445289/178303011-1135aed3-ca1f-442f-9f17-864c21e6e58c.png)

Item in the preview:
![image](https://user-images.githubusercontent.com/20445289/178303149-1672885f-1d33-4304-a4e7-ad9dffb9d3a7.png)
