### ISSUE TITLE
Prefix displays directly next to the text that comes after it.

### ISSUE THREAD

**Issue by ZepsiZola** [nulli0n/ExcellentCrates-spigot#33]
![image](https://user-images.githubusercontent.com/49735083/179215098-df287288-7f7e-4c61-afc3-b102f3a7bd2d.png)

As seen in the screenshot, the "Crates" prefix displays directly next to the text that comes after it. Also it is not coloured. This looks bad.

I'm on 4.0.5 on 1.19.

**Comment by Animationking11** [comment]
Go to your plugins folder
Then go to the ExcellentCrates folder
then open config.yml
then change Prefix (Its under plugin category) to your new message example:
   Prefix: '&bCreates | '

**Comment by nulli0n** [comment]
The solution is above.
