### ISSUE TITLE
Some settings reset everytime plugin reloads

### ISSUE THREAD

**Issue by panterathehacker** [nulli0n/ExcellentCrates-spigot#34]
Hi all,

Ever since the most recent update, we've had to stop using ExcellentCrates on our server as we attempt to understand this newest bug.

We have had 10 crates for a year now with no problem, but ever since the most recent update, some random configurations of each crate reset every time the plugin reloads (like during our daily server restarts). For example, the permission requirements of every crate turns off. The broadcasting for every reward turns off. Etc. I have attached a screenshot of what the console looks like when the plugin reloads.

Would appreciate any insight or advice into how to handle this! Thank you!

![image](https://user-images.githubusercontent.com/8600209/179364582-bd8f51d0-3e0b-4b6f-8bb6-d84d98a05c5f.png)

**Comment by panterathehacker** [comment]
Update: It seems like it is attempting to convert all the key files during every reload. When I delete all my key yml files and then reload, it successfully converts each of the keys and none of the configurations reset. But then when I reload _again_, it tries to convert the newly populated keys yml files and everything resets again.

**Comment by nulli0n** [comment]
Delete GoldenCrates folder.
