### ISSUE TITLE
Kick when setting block location

### ISSUE THREAD

**Issue by HerrFisch** [nulli0n/ExcellentCrates-spigot#36]
Hello, every time I add a block position or I type something in the crate editor in the chat, I get kicked
the message can be seen in the picture
I use the plugin version 4.0.5
![kickmessage](https://user-images.githubusercontent.com/77294046/180153391-09e0f64c-b5bc-4f8e-80dd-b064a759eb16.png)

**Comment by Animationking11** [comment]
it works fine for me I think its just you.

**Comment by Animationking11** [comment]
Can you show a video replicating the issue

**Comment by JacobWasTaken** [comment]
My friend and I are having the same issue

**Comment by nulli0n** [comment]
Update to 1.19.2
