### ISSUE TITLE
[BUG] Kick when entering anything in chat for the plugin

### ISSUE THREAD

**Issue by JacobWasTaken** [nulli0n/ExcellentCrates-spigot#39]
![2022-07-27_11 27 20](https://user-images.githubusercontent.com/102453197/181311469-1f3e3132-3312-4c8e-9802-22141801ae09.png)

![2022-07-27_11 28 00](https://user-images.githubusercontent.com/102453197/181311499-751866ba-35a9-40a7-ace6-d3ceb0d6b11a.png)

![image](https://user-images.githubusercontent.com/102453197/181311281-643567d2-35e7-4b6d-80f4-2330650f14cb.png)

To replicate, edit anything and type whatever in chat

**Comment by nulli0n** [comment]
Update to 1.19.2
