### ISSUE TITLE
Keys not removing themselves after opening 

### ISSUE THREAD

**Issue by alexanderb25** [nulli0n/ExcellentCrates-spigot#40]
Players can infinitely open crates with one key, the keys will not disappear. My players are clicking the dedicated crate chest and it instantly gives them the reward but it doesnt remove the key.

I got this console error when players open a crate: 

[Sun 10:18:51 ERROR Minecraft] Could not pass event PlayerInteractEvent to ExcellentCrates v4.0.4.1

**Comment by nulli0n** [comment]
Update to the latest plugin version.
