### ISSUE TITLE
Give Key All command repeating

### ISSUE THREAD

**Issue by SiuanSong** [nulli0n/ExcellentCrates-spigot#49]
**The Issue**
Give Key All command was repeating every minute after purchased from Tebex/Buycraft.

Last night players purchased keys for all from our store, the command repeated itself over and over each minute until the server was restarted.  Seems like the error was caused by no user data of a player within ExcellentCrates.
I have ran the command again today via the store, with that same user being online and it is working as intended.  Not sure if a one off error or not.  I could not repeat it, but thought I should report anyway.

**Environment**
ExcellentCrates v4.0.5
NexEngine v2.2.4 build-22/08/2022
1.19.2 Purpur #1766

**Error**
https://pastebin.com/2y700hhQ

**Comment by SiuanSong** [comment]
Can confirm this happened again.
https://pastebin.com/ENBkz07y

**Comment by nulli0n** [comment]
Install latest NexEngine: https://github.com/nulli0n/NexEngine-spigot/releases
