### ISSUE TITLE
GUI bug / item retrieval

### ISSUE THREAD

**Issue by OGreenC** [nulli0n/ExcellentCrates-spigot#51]
Hi,

A player of mine sent me this video, of him seemingly bugging GUI items out of the menu.
https://medal.tv/games/minecraft/clips/yZDW2-7s-UJ3T/d1337RAbp9NM?invite=cr-MSxTZ3EsNjY4OTAyOSw
~50s is the interesting part.

I confirmed that he was able to get these items ingame.

Any idea as to how this happened?
I have not been able to reproduce this particular error.

**Comment by nulli0n** [comment]
I can't reproduce it at all. More likely a plugin conflict.

**Comment by nulli0n** [comment]
Should be fixed in the latest plugin version.

**Comment by nulli0n** [comment]
Since no one can really reproduce this and due to lack of user feedback, issue will be closed.
