### ISSUE TITLE
Cost module not working

### ISSUE THREAD

**Issue by USBCharger** [nulli0n/ExcellentCrates-spigot#59]
Adding cost to open a crate doesn't seem to work. I tried to add exp cost, and it didn't work, I asked in the unofficial support Discord if anyone else had that issue and the person who runs it tested it and it didn't work for him either, including in game $ cost. 
(I'm running the latest version of excellentcrates/nexengine on paper 1.19)

**Comment by nulli0n** [comment]
You probably have bypass permissions.

**Comment by nulli0n** [comment]
Not confirmed. Works fine.
