### ISSUE TITLE
Issue with Creative Mode

### ISSUE THREAD

**Issue by VimaMT** [nulli0n/ExcellentCrates-spigot#6]
I'm using the latest version of Excellent Crates (GOOD plugin!), the latest version of Paper, and the latest version of Restricted Creative.

I go into /gmc using Restricted Creative, and I left-click my crate to see what is in it. I get a message stating that I am unable to do that in creative mode. I switch to /gms, then left-click. I cannot see anything in the crate.  I log off and back on, and I see 4 or 5 items from the crate laying on the ground around it.

I've been able to duplicate this twice. This will be an issue because I plan to give creative mode to players who advance far enough. They are not there yet.

**Comment by nulli0n** [comment]
The issue is on the Restricted Creative plugin side.
