### ISSUE TITLE
/excellentcrates comes back as %plugin% - Help

### ISSUE THREAD

**Issue by UsefullSpoon** [nulli0n/ExcellentCrates-spigot#62]
Basically whenever i try to do /excellentcrates help it comes back as %plugin% - help and %cmds%

![image](https://user-images.githubusercontent.com/96959805/202019261-48036b10-86bd-4565-917a-038d05f58635.png)

**Comment by nulli0n** [comment]
Reset /NexEngine/lang and it will be fixed.
