### ISSUE TITLE
Feature Request: Name and date on item rewards

### ISSUE THREAD

**Issue by ZepsiZola** [nulli0n/ExcellentCrates-spigot#63]
I think it would be nice to implement a feature in the plugin which allowed you to toggle whether you want "Obtainment Information" to be displayed in the lore of items that are obtained in crates. Of course this would only be good for certain "special" items as I wouldn't want this to be enabled when a player just gets some diamonds from a crate.

Example: A player gets a special item from a crate and in the lore of the item it says "Obtained by [player] on [date].".

I could do this on my own with PlaceholderAPI, but I'd have to change the format of every special item that is in my "Special Item Crate" since I could only work with PAPI by switching from directly giving an item to running a command that gives an item.
![image](https://user-images.githubusercontent.com/49735083/202537869-f4278bb6-28d0-4922-8949-441f9fbddde9.png)

**Comment by nulli0n** [comment]
An option in the config.yml would be enough?

**Comment by ZepsiZola** [comment]
> An option in the config.yml would be enough?

Yes that would be enough. Just a config option. Is this possible?
