### ISSUE TITLE
ExcellentCrates v4.0.6 not working with NexEngine v2.2.7

### ISSUE THREAD

**Issue by Kamilkime** [nulli0n/ExcellentCrates-spigot#64]
If I understand correctly - by removing [this method](https://github.com/nulli0n/NexEngine-spigot/commit/56cf60ec78356be2a4e403ed7666d8bec10abc0d#diff-51d4e5f8c894a76e73f8c06b967c4451c199d7766a0f086f65fca9410930a1beL242) you've broken [this part](https://github.com/nulli0n/ExcellentCrates-spigot/blob/master/src/main/java/su/nightexpress/excellentcrates/key/CrateKey.java#L51), thereby causing [this error](https://pastebin.com/KjFVH0hm)

**Comment by SkyKiller6363** [comment]
can confirm same issue on my server
https://pastebin.com/HfdLAW6z

**Comment by nulli0n** [comment]
Should be fixed now.
