### ISSUE TITLE
Players are able to open crates with a goat horn.

### ISSUE THREAD

**Issue by ZepsiZola** [nulli0n/ExcellentCrates-spigot#68]
https://cdn.discordapp.com/attachments/669916747742183475/1057778054451179571/Minecraft__1.19.1_2022-12-28_21-39-47.mp4

Basically this video depicts the issue completely. It doesn't actually open the crate with the crate winnings, but it does open the container that the crate is located at. Small issue. Not too urgent, but does come up every now and then.

**Comment by nulli0n** [comment]
Fixed!
