### ISSUE TITLE
Error when kicking a player when opening a crate

### ISSUE THREAD

**Issue by DrakMC** [nulli0n/ExcellentCrates-spigot#7]
When a player opens a crate and is kicked off the server, it gives an error, doesn't reward them or return their key. 

`[21:02:07 WARN]: [ExcellentCrates] Task #30264751 for ExcellentCrates v4.0.3.6 generated an exception
net.minecraft.server.CancelledPacketHandleException: null`

**Comment by nulli0n** [comment]
Update to the latest plugin & spigot build.
