### ISSUE TITLE
Option to disable opening crates with key in inventory (and only open with key in hand)

### ISSUE THREAD

**Issue by MCHalfAssed** [nulli0n/ExcellentCrates-spigot#70]
Hello, and Happy New Year!

Currently, if your key is in your inventory (and not in your hand), you can still open a crate. Could we have the option to make it so the key must be in your hand? Thanks!

**Comment by HeyFlay** [comment]
I agree please add this!

**Comment by nulli0n** [comment]
Yes, but what's the point?

**Comment by nulli0n** [comment]
Okay, will do

**Comment by MCHalfAssed** [comment]
> Okay, will do

Any updates on this request?

Even after adding warnings to the literal keys themselves, players are still accidently redeeming crates with the key being in their inventory lol.

**Comment by nulli0n** [comment]
Done in v4.1.8.
