### ISSUE TITLE
Crates block keeps getting reset after every server restart

### ISSUE THREAD

**Issue by Shyammc18** [nulli0n/ExcellentCrates-spigot#73]
So if i set a block as a crate and restart server that block isnt a crate anymore. Any fixes pls?

**Comment by Shyammc18** [comment]
@nulli0n ?

**Comment by nulli0n** [comment]
Send logs?

**Comment by Shyammc18** [comment]
> Send logs?

uh server logs?

**Comment by Shyammc18** [comment]
im not sure if this is the one ur asking for but anyways here
[latest.log](https://github.com/nulli0n/ExcellentCrates-spigot/files/10420414/latest.log)

**Comment by Shyammc18** [comment]
@nulli0n ?

**Comment by Shyammc18** [comment]
@nulli0n  reply pls

**Comment by nulli0n** [comment]
I'm unable to reproduce it. There is something wrong on your side.

**Comment by Shyammc18** [comment]
@nulli0n can i get ur discord
