### ISSUE TITLE
Why delete my LORE?

### ISSUE THREAD

**Issue by HaiXi2912** [nulli0n/ExcellentCrates-spigot#75]
get item no problem
![image](https://user-images.githubusercontent.com/98002490/215296893-382e714e-5f70-4578-9fb0-df27e9f0980f.png)
![image](https://user-images.githubusercontent.com/98002490/215296912-f9d85ca1-e7ef-498d-bf28-5f01c7610b45.png)
My lore is still here

but!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/98002490/215296943-9c6e63c2-2cbb-4139-bcbe-4201cfd0d887.png)
Why are there fewer items in the lottery?, I use mmoitems

After I updated the plug-in, some blank Lores of the original items were deleted. I was very angry because I wanted to recycle all the items and rollback the version. I would not update again until I repaired this bug!My exchange is invalid, including the items obtained by the player. Lore is confused

**Comment by nulli0n** [comment]
Try to disable PlaceholderAPI applying on reward items in config.yml

**Comment by HaiXi2912** [comment]
> Try to disable PlaceholderAPI applying on reward items in config.yml

https://github.com/nulli0n/ExcellentCrates-spigot/issues/75#issuecomment-1407574785

**Comment by HaiXi2912** [comment]
This bug has been resolved in my update to 4.1.6. A "PlaceholderAPI_For_Rewards" has been added in config.yml, which is closed by default, so my Lore will not be lost
