### ISSUE TITLE
Plugin Breaking

### ISSUE THREAD

**Issue by sirblazzit** [nulli0n/ExcellentCrates-spigot#76]
Basically daily, the plugin will stop working and throw this error when you try give a key:
[(https://pastebin.com/ENjL94An)]
and throw this error when a player joins:
[(https://pastebin.com/SaxjRFfs)]

Doing any command related to the plugin will do: An internal error occurred while attempting to perform this command and it's only fixed by doing a server restart.

**Comment by nulli0n** [comment]
Update Citizens.
