### ISSUE TITLE
Plugin breaks on v4.1.6

### ISSUE THREAD

**Issue by ZepsiZola** [nulli0n/ExcellentCrates-spigot#79]
Server version: 1.19.3 Purpur
Plugin Version: 4.1.5 & 4.1.6

I switched from version 4.1.5 to 4.1.6 last night and after the restart, players were not able to join the game.

I got this error message on start-up.
![image](https://user-images.githubusercontent.com/49735083/218077088-d2e93e87-3f18-484c-92f7-4198f1cf8da1.png)

And these error messages after start-up.
![image](https://user-images.githubusercontent.com/49735083/218077282-fcb954b8-3a13-47f2-b9ba-d994c82adbd8.png)

And these error messages whenever a player tried to join.
![image](https://user-images.githubusercontent.com/49735083/218077702-62fcd6c5-1f65-455e-82d1-12d06cd8ad2d.png)

**Comment by ZepsiZola** [comment]
FYI I downgraded back to 4.1.5 and players were able to join again so it definitely was this plugin.

**Comment by nulli0n** [comment]
Update to the latest version.
