### ISSUE TITLE
Bug: Names of item rewards break in crates.

### ISSUE THREAD

**Issue by ZepsiZola** [nulli0n/ExcellentCrates-spigot#81]
These images show the items that I put into the crate as rewards.
![image](https://user-images.githubusercontent.com/49735083/218231982-d04a7b54-9424-4e22-b957-af5d6782d22b.png)
![image](https://user-images.githubusercontent.com/49735083/218232089-3e84f701-cda4-49f0-ab7c-edd0edd7b4ad.png)

These are the items that players when they get that item in a crate.
![image](https://user-images.githubusercontent.com/49735083/218231968-5b7ec02f-639e-48b9-8e75-e80d28d7919e.png)
![image](https://user-images.githubusercontent.com/49735083/218232110-68da9d99-0bce-44b8-9741-4d7f59f471c8.png)

This seems to only happen when the reward has RGB formatting. Can this please be fixed.

**Comment by nulli0n** [comment]
Try to disable PlaceholderAPI for rewards in the config.yml (update to the latest version if you don't have such option)

**Comment by ZepsiZola** [comment]
I already have that set to false.
![image](https://user-images.githubusercontent.com/49735083/219222064-72141f9d-3c25-4de5-aad9-06d5b654b594.png)

**Comment by nulli0n** [comment]
Could you provide your crate config files?

**Comment by ZepsiZola** [comment]
https://www.toptal.com/developers/hastebin @nulli0n

**Comment by ZepsiZola** [comment]
I got to the bottom of this issue. It seems like this plugin handles RGB names for items a bit differently from vanilla minecraft behaviour. Basically what was happening was that I was using a custom item generator that omitted the formatting for the last character of the name. However, minecrafts default behaviour made it so that this was unnoticeable, and this error was only made noticeable because of the plugin handling the item data differently. Sorry for the hold up.
