### ISSUE TITLE
[Feature Request] Implement ZNPCs Support

### ISSUE THREAD

**Issue by R00tB33rMan** [nulli0n/ExcellentCrates-spigot#82]
Citizens are supported for crate binding; however, integrating ZNPCs would be more preferred for networks of my size, given Citizens becomes problematic when scaling with servers at over 300 concurrent players. The same: `Attached_Citizens: '{ID}'` line can be utilized in order to achieve this for consistency.

**Comment by Vrodo** [comment]
+1

**Comment by nulli0n** [comment]
Will do when it's updated to 1.19.4

**Comment by nulli0n** [comment]
Native NPC support has been removed, you have to assign crate commands to your NPCs using your NPC plugin whatever it is.
