### ISSUE TITLE
1.19.4 Block Names and Selecting a block

### ISSUE THREAD

**Issue by FractalingCoder** [nulli0n/ExcellentCrates-spigot#88]
When I open the editor and select the crate, any interactions (right clicking, left click etc.) do not work and/or work maybe 30% of the time? I can shift left click to toggle it but it wont work all the time. Clearing the crates text wont work either. 

When I click to bind a crate to a block, it will pull up the text on screen saying to select a block in game, but when I click a block for the first time, it will bind the create, but not exit editor mode, on the second time, it will pull up the crates drops, even though I am still in editor mode. 
https://user-images.githubusercontent.com/121209422/230505288-8b4bb65a-85ef-4201-85ee-33803b08a4b6.mp4

Also when transitioning from 1.19.3 to 1.19.4 all crates are deleted, not sure if that's a bug or a feature lol. Thanks in advance!

**Comment by nulli0n** [comment]
More likely a plugin conflict. Try it on a clean server.

**Comment by FractalingCoder** [comment]
Ya so there were a few plugins that were for 1.19.3 not 1.19.4 and were causing some errors so once I updated those all the crates came back so thanks!
