### ISSUE TITLE
Add support to Folia

### ISSUE THREAD

**Issue by Aitooor** [nulli0n/ExcellentCrates-spigot#92]
Here is the url from Folia: https://github.com/PaperMC/Folia

Let me know if it is possible please ❤️

**Comment by nulli0n** [comment]
> I expect basically zero plugins that are compatible with Paper to be compatible with Folia. However, there are plans to add API that would allow Folia plugins to be compatible with Paper.
I'm not gonna make another plugin version just for that fork, too much work for a doubtful project.

**Comment by BaiShenYaoDog** [comment]
try https://github.com/BaiShenYaoDog/ExcellentCrates-folia
