### ISSUE TITLE
If you skip animation it'll give you an extra reward if the first reward kills you.

### ISSUE THREAD

**Issue by DrakePork** [nulli0n/ExcellentCrates-spigot#94]
If you hit Escape to skip the animation, and the reward is death, the plugin will give you two rewards instead of one.

Heres hitting Escape to end animation early:
![image](https://user-images.githubusercontent.com/29175884/233776664-85cd45eb-df87-4c3a-b3d9-422bd066da5e.png)

Here's if you wait for the animation to complete (Working as intended):
![image](https://user-images.githubusercontent.com/29175884/233776701-d5dc8112-d0e6-458c-b3b1-3770b05c9f26.png)

Was tested on a spigot server with no other plugins than ExcellentCrates and NexEngine.

I originally found it because if you have a plugin that changes /kill, like Essentials or CMI, it'll spam you with nearly every single reward in the entire crate: (video of Essentials, ExcellentCrates & NexEngine only)
https://user-images.githubusercontent.com/29175884/233777028-a692ebde-8d18-41c2-a084-59e0d2cf7106.mp4

With this error if you run it with CMI (No console error if you have Essentials): https://mclo.gs/Nl4i5B5

**Comment by nulli0n** [comment]
Fixed in v5.0.0
