### ISSUE TITLE
Oraxen compatibility

### ISSUE THREAD

**Issue by ktoviektosom** [nulli0n/ExcellentCrates-spigot#96]
Hello, I have problem... We use the ExcellentCrates plugin and we have purchased models for custom crates, the problem occurs when we place the crate, set it up and in survival gamemode we want to open the reward preview but we hold the left button a little longer... The crate is destroyed, even though it has a crate set on it via ExcellentCrates... what is that? can it be fixed? maybe the region would help, but I'd like to fix it anyway

**Comment by nulli0n** [comment]
Not a crates issue.
