### ISSUE TITLE
Excellent Crates Editor GUI broken 4.2.0

### ISSUE THREAD

**Issue by Xipher81** [nulli0n/ExcellentCrates-spigot#97]
Server Info
Minecraft server version 1.19.3
Paper version git-Paper-447 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18470db)
ExcellentCrates 4.1.7

I recently updated to the new version 4.2.0 opened the GUI /excellentcrates editor GUI opened however I am not able to enter into the crate editor or key editor when selection the icon. I reset all data on the plugin and started with a fresh config. Still was not able to open the GUI to create a crate or key. At this point I rolled back the version to 4.1.10 didn't work here either. After reading the change log I decided to roll back to 4.1.8 where the fix to virtual keys was made and still no dice. So I rolled back one more time to 4.1.7 and GUI editor worked again.

**Comment by nulli0n** [comment]
Update NexEngine.
