### ISSUE TITLE
Duplicate DB entries

### ISSUE THREAD

**Issue by Masuary** [nulli0n/ExcellentCrates-spigot#98]
Sometimes players have one of the chests twice in their DB.

It would have 2x daily or 2x weekly, and the plugin doesn't like that.

Could there be a fix for when this happens it will delete 1 of the two duplicate entries.

**Comment by Masuary** [comment]
see

https://discord.com/channels/903053383475277844/960838816682360874/1102669890952900758

inside your discord

**Comment by nulli0n** [comment]
Forge is not supported.
