### ISSUE TITLE
[FEATURE] Separate Inventory Title and Message Name

### ISSUE THREAD

**Issue by test137E29B** [nulli0n/ExcellentCrates-spigot#99]
For server usage, it would be nice to have an additional crate configuration option to change the Inventory Name separately from the name used in messages. I would like to use a custom inventory header created in ItemsAdder, which shows as an emote, but changes how the inventory looks such as this but with the crate name on:

![image](https://github.com/nulli0n/ExcellentCrates-spigot/assets/37277599/ef710929-914e-4547-bad5-09c2a273b5a7)

Unfortunately setting this to the display name would also show in chat this header instead of a nicely chat formatted name, which makes it not currently possible.

**Comment by nulli0n** [comment]
Where exactly?

**Comment by test137E29B** [comment]
The same place you set the Crate's Name, a separate option to set the Crate's inventory title. If not set it could use the name, but adding an optional setting to change it to use an emote makes the inventory header like the image above.

If you change the name to like the image above, it shows the whole emote in chat, which is a bad thing of course.

**Comment by nulli0n** [comment]
Can be done by editing preview config file.
